/* This file was generated by SableCC (http://www.sablecc.org/). */

package parser.node;

import parser.analysis.*;

@SuppressWarnings("nls")
public final class AGtExpr extends PExpr
{
    private TIdent _var_;
    private PExpr _expr_;

    public AGtExpr()
    {
        // Constructor
    }

    public AGtExpr(
        @SuppressWarnings("hiding") TIdent _var_,
        @SuppressWarnings("hiding") PExpr _expr_)
    {
        // Constructor
        setVar(_var_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new AGtExpr(
            cloneNode(this._var_),
            cloneNode(this._expr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGtExpr(this);
    }

    public TIdent getVar()
    {
        return this._var_;
    }

    public void setVar(TIdent node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((TIdent) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
