/* This file was generated by SableCC (http://www.sablecc.org/). */

package parser.node;

import java.util.*;
import parser.analysis.*;

@SuppressWarnings("nls")
public final class AHead extends PHead
{
    private TIdent _name_;
    private final LinkedList<TIdent> _params_ = new LinkedList<TIdent>();

    public AHead()
    {
        // Constructor
    }

    public AHead(
        @SuppressWarnings("hiding") TIdent _name_,
        @SuppressWarnings("hiding") List<?> _params_)
    {
        // Constructor
        setName(_name_);

        setParams(_params_);

    }

    @Override
    public Object clone()
    {
        return new AHead(
            cloneNode(this._name_),
            cloneList(this._params_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHead(this);
    }

    public TIdent getName()
    {
        return this._name_;
    }

    public void setName(TIdent node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public LinkedList<TIdent> getParams()
    {
        return this._params_;
    }

    public void setParams(List<?> list)
    {
        for(TIdent e : this._params_)
        {
            e.parent(null);
        }
        this._params_.clear();

        for(Object obj_e : list)
        {
            TIdent e = (TIdent) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._params_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._params_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._params_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((TIdent) newChild);
            return;
        }

        for(ListIterator<TIdent> i = this._params_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TIdent) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
