/* This file was generated by SableCC (http://www.sablecc.org/). */

package parser.node;

import java.util.*;
import parser.analysis.*;

@SuppressWarnings("nls")
public final class AProg extends PProg
{
    private final LinkedList<PRule> _rules_ = new LinkedList<PRule>();

    public AProg()
    {
        // Constructor
    }

    public AProg(
        @SuppressWarnings("hiding") List<?> _rules_)
    {
        // Constructor
        setRules(_rules_);

    }

    @Override
    public Object clone()
    {
        return new AProg(
            cloneList(this._rules_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProg(this);
    }

    public LinkedList<PRule> getRules()
    {
        return this._rules_;
    }

    public void setRules(List<?> list)
    {
        for(PRule e : this._rules_)
        {
            e.parent(null);
        }
        this._rules_.clear();

        for(Object obj_e : list)
        {
            PRule e = (PRule) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._rules_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rules_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rules_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PRule> i = this._rules_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PRule) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
