/* This file was generated by SableCC (http://www.sablecc.org/). */

package parser.node;

import parser.analysis.*;

@SuppressWarnings("nls")
public final class AWildcardExpr extends PExpr
{
    private TWildcard _wildcard_;

    public AWildcardExpr()
    {
        // Constructor
    }

    public AWildcardExpr(
        @SuppressWarnings("hiding") TWildcard _wildcard_)
    {
        // Constructor
        setWildcard(_wildcard_);

    }

    @Override
    public Object clone()
    {
        return new AWildcardExpr(
            cloneNode(this._wildcard_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWildcardExpr(this);
    }

    public TWildcard getWildcard()
    {
        return this._wildcard_;
    }

    public void setWildcard(TWildcard node)
    {
        if(this._wildcard_ != null)
        {
            this._wildcard_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._wildcard_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._wildcard_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._wildcard_ == child)
        {
            this._wildcard_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._wildcard_ == oldChild)
        {
            setWildcard((TWildcard) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
